### PR TITLE
feat: zeva-133 - use assessed supplemental values in compliance table

### PR DESCRIPTION
**Pull request by tim738745**

### CODE REVIEW

**Review by AlexZorkin — APPROVED** [review]
One thing that would help for reviews is to keep any linting changes out of feature prs.

**Comment by tim738745** [comment]
> One thing that would help for reviews is to keep any linting changes out of feature prs.

got it!

**Comment by AlexZorkin** [comment]
There's a merge conflict with your previous ticket, please update with a fix :)

**Comment by tim738745** [comment]
> There's a merge conflict with your previous ticket, please update with a fix :)

Done!

**Pull request merged**
